### ISSUE TITLE
weird scrolling on creating view

### ISSUE THREAD

**Issue by kibotu** [chuross/expandable-layout#1]
i have a recyclerview that contains a list of expandable-layouts which contain each another recyclerview

and when i create the fragment it scrolls automatically:

https://imgur.com/9l0nZZK

i have set the recyclerviews to fixed size and removed all animators/animations still this happens

weirdly it happens only in release builds, in debug builds everything works perfectly fine, i'm using latest support library 27.1.0, build tools 27.0.3, gradle build tools 3.1.0, kotlin 1.2.31

any idea how i can fix this?

any help is highly appreciated

**Comment by chuross** [comment]
Do you have any example code?
I'll check it, and fix this issue.

thank you. 👍

**Comment by kibotu** [comment]
yea i'll prepare something next week, thanks for looking into it

**Comment by kibotu** [comment]
was resolved by adding the following to the recyclerview: 

      android:descendantFocusability="blocksDescendants"

(sauce: https://stackoverflow.com/a/40492486/1006741)
